services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resersportif-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: resersportif-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend